# Generated by Django 4.0.6 on 2022-07-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_url_slug', models.SlugField(default='')),
                ('tool_title', models.CharField(max_length=255)),
                ('tool_iframe_url', models.CharField(max_length=255)),
            ],
        ),
    ]
