# Generated by Django 4.0.6 on 2022-07-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='tool_url_slug',
            new_name='slug',
        ),
    ]
