# Generated by Django 4.0.6 on 2022-10-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_tool_url_slug_tool_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_supporting_script_source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
