# Generated by Django 4.0.6 on 2022-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_tool_tool_supporting_script_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tool_iframe_class',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_iframe_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
